name:                cs194-introduction-to-haskell
version:             0.1.0.0
github:              "BoeingX/cs194-introduction-to-haskell"
license:             BSD3
author:              "BoeingX"
maintainer:          "user@domain.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/BoeingX/cs194-introduction-to-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- hspec

library:
  source-dirs: src

executables:
  cs194-introduction-to-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs194-introduction-to-haskell

tests:
  cs194-introduction-to-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs194-introduction-to-haskell
